language: node_js
# Better headless-gl support on macOS.
os: osx
node_js:
  # Latest prebuilt binary from https://github.com/stackgl/headless-gl/releases.
  - "12"
env:
  global:
    - CI=1
install:
  - npm i -g lerna
  - lerna bootstrap
  - lerna link
before_script:
  - npm run dist
script:
  - npm test
after_success:
  - npm run coverage:report
